language: ruby
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global:
  - secure: dcznqpA02SPckK5m1f2ASmI5UIIPexY8KlBI5R8e0LKC/v4E92zIwuWXBc3viBxALP00z7m5YYYM5Sgu53UuW4+bUr6y2ASwrZxSlaZ1dZSOJGc+KH+KygUewa1eFWRV15BxfWp4jCIGo+vX5giWNG2mohB4RmuUOxfbKnddZTw=
